import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

import localFont from "next/font/local";

const fontImpertor = localFont({
  src: "../public/fonts/Imperator.ttf",
  variable: "--font-imperator",
});

const fontMetroplis = localFont({
  src: "../public/fonts/Metropolis-Regular.otf",
  variable: "--font-metropolis",
});

const fontImperatorVanila = localFont({
  src: "../public/fonts/Imperator.ttf",
  variable: "--font-imperator-vanila",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontImpertor.variable} ${fontMetroplis.variable} ${fontImperatorVanila.variable} antialiased`}
      >
        <Navbar />
        {children} <Footer />
      </body>
    </html>
  );
}
